/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kfilereplace.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "kfilereplaceadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class KfilereplaceAdaptor
 */

KfilereplaceAdaptor::KfilereplaceAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KfilereplaceAdaptor::~KfilereplaceAdaptor()
{
    // destructor
}

void KfilereplaceAdaptor::openURL(const QString &url)
{
    // handle method call org.kde.kfilereplace.openURL
    QMetaObject::invokeMethod(parent(), "openURL", Q_ARG(QString, url));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->openURL(url);
}


#include "kfilereplaceadaptor.moc"
