/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kfilereplace.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef KFILEREPLACEADAPTOR_H_128601150119640
#define KFILEREPLACEADAPTOR_H_128601150119640

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kfilereplace
 */
class KfilereplaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kfilereplace")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kfilereplace\" >\n"
"    <method name=\"openURL\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    KfilereplaceAdaptor(QObject *parent);
    virtual ~KfilereplaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void openURL(const QString &url);
Q_SIGNALS: // SIGNALS
};

#endif
